version: '3.1'

services:

  db:
    image: postgres:alpine
    volumes:
      - ./.docker/volumes/pgdata:/var/lib/postgresql/data

  app:
    build: .
    volumes:
      - ./:/usr/src/app
    ports:
      - 4000:4000
